name: CMake CI

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake
        cmake --version
        g++ --version
        
    - name: Show structure
      run: ls -R
        
    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build build --verbose

    - name: Run
      run: |
        ./build/hello_world_app
        ./build/solver_app
